---
- name: Run common set up
  hosts: all
  become: true
  roles:
    - common

- name: Set up app
  hosts: app_server
  vars_files:
    - secrets.vault
    - vars.yml
  become: true
  roles:
    - app_setup

- name: Set up Postgres DB
  hosts: db_server
  vars_files:
    - secrets.vault
    - vars.yml
  become: true
  roles:
    - db_setup

- name: Set up Upstash
  hosts: upstash_server
  vars_files:
    - secrets.vault
    - vars.yml
  become: true
  roles:
    - upstash_setup

- name: Set up proxy
  hosts: proxy_server
  become: true
  roles:
    - proxy_setup
