---
- name: Run common set up
  tags: always
  hosts: all
  become: true
  roles:
    - common


- name: Set up Postgres DB
  tags: db
  hosts: db_server
  vars_files:
    - secrets.vault
    - vars.yml
  become: true
  roles:
    - db_setup

- name: Set up Upstash
  tags: upstash
  hosts: upstash_server
  vars_files:
    - secrets.vault
    - vars.yml
  become: true
  roles:
    - upstash_setup

- name: Set up app
  tags: app
  hosts: app_server
  vars_files:
    - secrets.vault
    - vars.yml
  become: true
  roles:
    - app_setup

- name: Set up proxy
  tags: proxy
  hosts: proxy_server
  become: true
  roles:
    - proxy_setup
