postgresql_host: "db"
upstash_host: "upstash"

migrate: false
seed: false

nodejs_version: 20

app_name: "jira-clone"

apps_group: "apps"
apps_user: "apps"
apps_home: "/home/apps"

git_repo_url: "https://github.com/cycleglorious/jira_clone.git"
source_code_path: "{{ apps_home }}/source-{{ app_name }}"
artifact_path: "{{ apps_home }}/{{ app_name }}"
artifact_name: "{{ app_name }}.zip"
