- name: Install the GPG key for Node.js LTS
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the Node.js LTS repository
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Install Node.js
  ansible.builtin.apt:
    pkg:
      - nodejs
    state: present
