- name: Install Node.js
  ansible.builtin.include_tasks: install-node.yml

- name: Create user
  ansible.builtin.include_tasks: create-user.yml

- name: Migrate or seed DB
  ansible.builtin.include_tasks: migrate-db.yml
  run_once: true
  when: migrate or seed

- name: Get artifact
  ansible.builtin.include_tasks: get-artifact.yml

- name: Set up and start PM2
  ansible.builtin.include_tasks: start-pm2.yml
