- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce and docker-compose-plugin
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-compose-plugin
    state: present

- name: Create upstash directory
  ansible.builtin.file:
    path: /home/vagrant/upstash
    state: directory
    mode: '0755'

- name: Create docker-compose.yml file from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/vagrant/upstash/docker-compose.yml
    mode: '0644'

- name: Create and deploy docker compose services
  community.docker.docker_compose_v2:
    project_src: /home/vagrant/upstash/
    files: docker-compose.yml
