- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker-ce and docker-compose-plugin 
  apt:
    pkg: 
      - docker-ce
      - docker-compose-plugin
    state: latest

- name: Create upstash directory
  file:
    path: /home/vagrant/upstash
    state: directory

- name: Create docker-compose.yml file from template
  template:
    src: docker-compose.yml.j2
    dest: /home/vagrant/upstash/docker-compose.yml

- name: Create and deploy docker compose services
  community.docker.docker_compose_v2:
    project_src: /home/vagrant/upstash/
    files: docker-compose.yml


